---
title: "Assignment 1: Introduction"
author: "Sammy DiLoreto"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assigment section on Sakai.


## 1) Finish setting up R Studio

### Install TinyTex
Now, run this code cell the same way. This will install "tinytex" -- a helper app that allows you to knit your markdown documents into professional quality PDFs.
```{r install tiny tex, eval=FALSE, include=FALSE}
#install tinytext
tinytex::install_tinytex()
```

### Set your default knit directory
This setting will help deal with relative paths later on...
 - From the Tool menu, select `Global Options`
 - Select the RMarkdown section
 - In the "Evaluate chunks in directory", set the option to "Project" --> I did not have this option 


## 2) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I've taken Geospatial Data Analytics (ENV 859) where we used Python and Git for preparing and running geospatial analyses. I used R for statistical analyses in ENV 710, ENV 537 (Environmental Health and Epidemiology), and for a summer research project with Duke's Superfund Research Center. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident navigating R studio and Git because of my previous experience in classes. I'm pretty comfortable with general coding because of my experience with python in ENV 859.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I'm apprehensive about learning all the terminology, but I think it will come with time. I'm also a little worried about using my own computer because if I do run into any issues, it may be difficult for the instructors to fix. 


## 3) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course Rmd file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/sammydiloreto/EDA-Spring2023.git 

## 4) Knitting
When you have completed this document, click the `knit` button. This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
